package projectsemester2;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class JobScheduleGUI extends javax.swing.JFrame {

    /**
     * Creates new form TestJobSchedule
     */
        ArrayList <JobSchedule> list = new ArrayList <> ();
        Staff staff; 
        JobSchedule js;
        //variable declaration
        int morningStaff;
        int middleStaff;
        int eveningStaff;
        String name;
        String staffID;
        String duty;
        String shiftday1;
        String shiftday2;
        String shiftday3;
        String shiftday4;
        String shiftday5;
        String shiftday6;
        String shiftday7;
        String header;
        
    public JobScheduleGUI() {
        
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        ColourBGPNL = new javax.swing.JPanel();
        restaurantNameLBL = new javax.swing.JLabel();
        ShiftDetailsPNL = new javax.swing.JPanel();
        morningStaffLBL = new javax.swing.JLabel();
        middleStaffLBL = new javax.swing.JLabel();
        eveningStaffLBL = new javax.swing.JLabel();
        morningStaffTF = new javax.swing.JTextField();
        middleStaffTF = new javax.swing.JTextField();
        eveningStaffTF = new javax.swing.JTextField();
        OKbtn = new javax.swing.JButton();
        resetShiftBTN = new javax.swing.JButton();
        shiftDetailsLBL = new javax.swing.JLabel();
        searchPNL = new javax.swing.JPanel();
        searchNameTF = new javax.swing.JTextField();
        searchBTN = new javax.swing.JButton();
        searchNameLBL = new javax.swing.JLabel();
        shiftTimeLBL = new javax.swing.JLabel();
        detailsShiftLBL = new javax.swing.JLabel();
        staffDetailsandShiftPNL = new javax.swing.JPanel();
        nameLBL = new javax.swing.JLabel();
        staffIDLBL = new javax.swing.JLabel();
        dutyLBL = new javax.swing.JLabel();
        staffNameTF = new javax.swing.JTextField();
        staffIDTF = new javax.swing.JTextField();
        mondayLBL = new javax.swing.JLabel();
        tuesdayLBL = new javax.swing.JLabel();
        wednesdayLBL = new javax.swing.JLabel();
        thursdayLBL = new javax.swing.JLabel();
        fridayLBL = new javax.swing.JLabel();
        saturdayLBL = new javax.swing.JLabel();
        sundayLBL = new javax.swing.JLabel();
        shiftMondayTF = new javax.swing.JTextField();
        shiftTuesdayTF = new javax.swing.JTextField();
        shiftWedTF = new javax.swing.JTextField();
        shiftThursdayTF = new javax.swing.JTextField();
        shiftFridayTF = new javax.swing.JTextField();
        shiftSatTF = new javax.swing.JTextField();
        shiftSundayTF = new javax.swing.JTextField();
        dutyCB = new javax.swing.JComboBox();
        addBTN = new javax.swing.JButton();
        resetBTN = new javax.swing.JButton();
        updatePNL = new javax.swing.JPanel();
        updateBTN = new javax.swing.JButton();
        editedNameTF = new javax.swing.JTextField();
        editNameLBL = new javax.swing.JLabel();
        shiftAndTimePNL = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        shiftLBL = new javax.swing.JLabel();
        timeLBL = new javax.swing.JLabel();
        morningLBL = new javax.swing.JLabel();
        middleLBL = new javax.swing.JLabel();
        eveningLBL = new javax.swing.JLabel();
        morningTimeLBL = new javax.swing.JLabel();
        middleTimeLBL = new javax.swing.JLabel();
        eveningTimeLBL = new javax.swing.JLabel();
        staffSchedulePNL = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        displayBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        deletePNL = new javax.swing.JPanel();
        nameDeletedTF = new javax.swing.JTextField();
        deleteBTN = new javax.swing.JButton();
        deletedNameLBL = new javax.swing.JLabel();
        staffScheduleLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                                                                                                     Job Schedule");
        setBackground(new java.awt.Color(255, 204, 204));

        ColourBGPNL.setBackground(new java.awt.Color(255, 255, 255));
        ColourBGPNL.setLayout(null);

        restaurantNameLBL.setBackground(new java.awt.Color(255, 255, 255));
        restaurantNameLBL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        restaurantNameLBL.setText("CHE SITI WAN KEMBANG RESTAURANT");
        ColourBGPNL.add(restaurantNameLBL);
        restaurantNameLBL.setBounds(374, 16, 363, 22);

        ShiftDetailsPNL.setBackground(new java.awt.Color(255, 204, 204));
        ShiftDetailsPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        morningStaffLBL.setText("Morning shift staff :");

        middleStaffLBL.setText("Middle shift staff :");

        eveningStaffLBL.setText("Evening shift staff :");

        OKbtn.setBackground(new java.awt.Color(255, 153, 204));
        OKbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsemester2/Accept-icon.png"))); // NOI18N
        OKbtn.setText("OK");
        OKbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbtnActionPerformed(evt);
            }
        });

        resetShiftBTN.setBackground(new java.awt.Color(255, 153, 204));
        resetShiftBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsemester2/Apps-Dialog-Refresh-icon.png"))); // NOI18N
        resetShiftBTN.setText("Reset Shift");
        resetShiftBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetShiftBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShiftDetailsPNLLayout = new javax.swing.GroupLayout(ShiftDetailsPNL);
        ShiftDetailsPNL.setLayout(ShiftDetailsPNLLayout);
        ShiftDetailsPNLLayout.setHorizontalGroup(
            ShiftDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShiftDetailsPNLLayout.createSequentialGroup()
                .addGroup(ShiftDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShiftDetailsPNLLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(ShiftDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(ShiftDetailsPNLLayout.createSequentialGroup()
                                .addGroup(ShiftDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(morningStaffLBL)
                                    .addComponent(middleStaffLBL))
                                .addGap(16, 16, 16)
                                .addGroup(ShiftDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(morningStaffTF, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(middleStaffTF)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ShiftDetailsPNLLayout.createSequentialGroup()
                                .addComponent(eveningStaffLBL)
                                .addGap(18, 18, 18)
                                .addComponent(eveningStaffTF)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ShiftDetailsPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resetShiftBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OKbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ShiftDetailsPNLLayout.setVerticalGroup(
            ShiftDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShiftDetailsPNLLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(ShiftDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(morningStaffLBL)
                    .addComponent(morningStaffTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ShiftDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShiftDetailsPNLLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(middleStaffLBL))
                    .addGroup(ShiftDetailsPNLLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(middleStaffTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(ShiftDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShiftDetailsPNLLayout.createSequentialGroup()
                        .addGap(18, 24, Short.MAX_VALUE)
                        .addComponent(eveningStaffLBL)
                        .addGap(30, 30, 30))
                    .addGroup(ShiftDetailsPNLLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(eveningStaffTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(ShiftDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetShiftBTN)
                    .addComponent(OKbtn))
                .addGap(28, 28, 28))
        );

        ColourBGPNL.add(ShiftDetailsPNL);
        ShiftDetailsPNL.setBounds(22, 80, 275, 236);

        shiftDetailsLBL.setBackground(new java.awt.Color(255, 255, 255));
        shiftDetailsLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        shiftDetailsLBL.setText("Shift Details");
        ColourBGPNL.add(shiftDetailsLBL);
        shiftDetailsLBL.setBounds(22, 54, 130, 26);

        searchPNL.setBackground(new java.awt.Color(255, 204, 204));
        searchPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameTFActionPerformed(evt);
            }
        });

        searchBTN.setBackground(new java.awt.Color(255, 153, 204));
        searchBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsemester2/Zoom-icon.png"))); // NOI18N
        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        searchNameLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        searchNameLBL.setText("Enter staff name to search :");

        javax.swing.GroupLayout searchPNLLayout = new javax.swing.GroupLayout(searchPNL);
        searchPNL.setLayout(searchPNLLayout);
        searchPNLLayout.setHorizontalGroup(
            searchPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPNLLayout.createSequentialGroup()
                .addGroup(searchPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPNLLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(searchNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchNameLBL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPNLLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        searchPNLLayout.setVerticalGroup(
            searchPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPNLLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(searchNameLBL)
                .addGap(27, 27, 27)
                .addComponent(searchNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(searchBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ColourBGPNL.add(searchPNL);
        searchPNL.setBounds(321, 344, 300, 200);

        shiftTimeLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        shiftTimeLBL.setText("Shift & Time");
        ColourBGPNL.add(shiftTimeLBL);
        shiftTimeLBL.setBounds(321, 59, 89, 16);

        detailsShiftLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        detailsShiftLBL.setText("Staff Details & Shift");
        ColourBGPNL.add(detailsShiftLBL);
        detailsShiftLBL.setBounds(639, 59, 176, 16);

        staffDetailsandShiftPNL.setBackground(new java.awt.Color(255, 204, 204));
        staffDetailsandShiftPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nameLBL.setText("Name :");

        staffIDLBL.setText("Staff ID :");

        dutyLBL.setText("Duty :");

        mondayLBL.setText("Monday : ");

        tuesdayLBL.setText("Tuesday :");

        wednesdayLBL.setText("Wednesday :");

        thursdayLBL.setText("Thursday :");

        fridayLBL.setText("Friday :");

        saturdayLBL.setText("Saturday :");

        sundayLBL.setText("Sunday :");

        dutyCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KITCHEN", "LOBBY" }));
        dutyCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dutyCBActionPerformed(evt);
            }
        });

        addBTN.setBackground(new java.awt.Color(255, 153, 204));
        addBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsemester2/Button-Add-icon.png"))); // NOI18N
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        resetBTN.setBackground(new java.awt.Color(255, 153, 204));
        resetBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsemester2/Button-Reload-icon.png"))); // NOI18N
        resetBTN.setText("Reset");
        resetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTNActionPerformed(evt);
            }
        });

        updatePNL.setBackground(new java.awt.Color(204, 204, 204));
        updatePNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        updateBTN.setBackground(new java.awt.Color(255, 153, 204));
        updateBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsemester2/Actions-document-edit-icon.png"))); // NOI18N
        updateBTN.setText("Update");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });

        editNameLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        editNameLBL.setText("Enter staff name to be updated :");

        javax.swing.GroupLayout updatePNLLayout = new javax.swing.GroupLayout(updatePNL);
        updatePNL.setLayout(updatePNLLayout);
        updatePNLLayout.setHorizontalGroup(
            updatePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePNLLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editNameLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(updatePNLLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(editedNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updatePNLLayout.setVerticalGroup(
            updatePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePNLLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(editNameLBL)
                .addGap(18, 18, 18)
                .addComponent(editedNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(updateBTN)
                .addContainerGap())
        );

        javax.swing.GroupLayout staffDetailsandShiftPNLLayout = new javax.swing.GroupLayout(staffDetailsandShiftPNL);
        staffDetailsandShiftPNL.setLayout(staffDetailsandShiftPNLLayout);
        staffDetailsandShiftPNLLayout.setHorizontalGroup(
            staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffDetailsandShiftPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffDetailsandShiftPNLLayout.createSequentialGroup()
                        .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(staffDetailsandShiftPNLLayout.createSequentialGroup()
                                .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mondayLBL)
                                    .addComponent(tuesdayLBL))
                                .addGap(30, 30, 30)
                                .addComponent(shiftMondayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(staffDetailsandShiftPNLLayout.createSequentialGroup()
                                .addComponent(dutyLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dutyCB, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(staffDetailsandShiftPNLLayout.createSequentialGroup()
                                .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(staffIDLBL)
                                    .addComponent(nameLBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(staffNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(staffDetailsandShiftPNLLayout.createSequentialGroup()
                                        .addComponent(staffIDTF)
                                        .addGap(46, 46, 46)))))
                        .addGap(18, 18, 18)
                        .addComponent(updatePNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(staffDetailsandShiftPNLLayout.createSequentialGroup()
                        .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wednesdayLBL)
                            .addComponent(thursdayLBL)
                            .addComponent(fridayLBL)
                            .addComponent(sundayLBL)
                            .addComponent(saturdayLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shiftWedTF, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(shiftTuesdayTF)
                            .addComponent(shiftThursdayTF)
                            .addComponent(shiftFridayTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(shiftSatTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(shiftSundayTF))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(staffDetailsandShiftPNLLayout.createSequentialGroup()
                        .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        staffDetailsandShiftPNLLayout.setVerticalGroup(
            staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffDetailsandShiftPNLLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffDetailsandShiftPNLLayout.createSequentialGroup()
                        .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLBL)
                            .addComponent(staffNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staffIDLBL)
                            .addComponent(staffIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dutyLBL)
                            .addComponent(dutyCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mondayLBL)
                            .addComponent(shiftMondayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tuesdayLBL)
                            .addComponent(shiftTuesdayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shiftWedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wednesdayLBL))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(staffDetailsandShiftPNLLayout.createSequentialGroup()
                        .addComponent(updatePNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGap(16, 16, 16)
                .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shiftThursdayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thursdayLBL))
                .addGap(16, 16, 16)
                .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fridayLBL)
                    .addComponent(shiftFridayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shiftSatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saturdayLBL))
                .addGap(16, 16, 16)
                .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shiftSundayTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sundayLBL, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(staffDetailsandShiftPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(resetBTN))
                .addContainerGap())
        );

        ColourBGPNL.add(staffDetailsandShiftPNL);
        staffDetailsandShiftPNL.setBounds(640, 80, 540, 490);

        shiftAndTimePNL.setBackground(new java.awt.Color(255, 204, 204));
        shiftAndTimePNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        shiftLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        shiftLBL.setText("Shift");

        timeLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        timeLBL.setText("Time");

        morningLBL.setText("Morning");

        middleLBL.setText("Middle");

        eveningLBL.setText("Evening");

        morningTimeLBL.setText("9AM - 6PM");

        middleTimeLBL.setText("12PM - 8PM");

        eveningTimeLBL.setText("2PM - 11PM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shiftLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(morningLBL)
                    .addComponent(middleLBL)
                    .addComponent(eveningLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(morningTimeLBL)
                        .addComponent(middleTimeLBL)
                        .addComponent(eveningTimeLBL))
                    .addComponent(timeLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shiftLBL)
                    .addComponent(timeLBL))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(morningLBL)
                    .addComponent(morningTimeLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleLBL)
                    .addComponent(middleTimeLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eveningLBL)
                    .addComponent(eveningTimeLBL))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout shiftAndTimePNLLayout = new javax.swing.GroupLayout(shiftAndTimePNL);
        shiftAndTimePNL.setLayout(shiftAndTimePNLLayout);
        shiftAndTimePNLLayout.setHorizontalGroup(
            shiftAndTimePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shiftAndTimePNLLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        shiftAndTimePNLLayout.setVerticalGroup(
            shiftAndTimePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shiftAndTimePNLLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        ColourBGPNL.add(shiftAndTimePNL);
        shiftAndTimePNL.setBounds(321, 80, 300, 244);

        staffSchedulePNL.setBackground(new java.awt.Color(255, 204, 204));
        staffSchedulePNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOutput.setEditable(false);
        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        displayBTN.setBackground(new java.awt.Color(255, 153, 204));
        displayBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsemester2/Programming-Show-Property-icon.png"))); // NOI18N
        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        exitBTN.setBackground(new java.awt.Color(255, 153, 204));
        exitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsemester2/Users-Exit-icon.png"))); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout staffSchedulePNLLayout = new javax.swing.GroupLayout(staffSchedulePNL);
        staffSchedulePNL.setLayout(staffSchedulePNLLayout);
        staffSchedulePNLLayout.setHorizontalGroup(
            staffSchedulePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffSchedulePNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffSchedulePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(staffSchedulePNLLayout.createSequentialGroup()
                        .addComponent(displayBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        staffSchedulePNLLayout.setVerticalGroup(
            staffSchedulePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffSchedulePNLLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(staffSchedulePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayBTN)
                    .addComponent(exitBTN))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        ColourBGPNL.add(staffSchedulePNL);
        staffSchedulePNL.setBounds(22, 619, 1162, 337);

        deletePNL.setBackground(new java.awt.Color(255, 204, 204));
        deletePNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        deleteBTN.setBackground(new java.awt.Color(255, 153, 204));
        deleteBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsemester2/Button-Close-icon.png"))); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        deletedNameLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deletedNameLBL.setText("Enter staff name to be deleted :");

        javax.swing.GroupLayout deletePNLLayout = new javax.swing.GroupLayout(deletePNL);
        deletePNL.setLayout(deletePNLLayout);
        deletePNLLayout.setHorizontalGroup(
            deletePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePNLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(deletePNLLayout.createSequentialGroup()
                .addGroup(deletePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletePNLLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(nameDeletedTF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deletePNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deletedNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deletePNLLayout.setVerticalGroup(
            deletePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePNLLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(deletedNameLBL)
                .addGap(26, 26, 26)
                .addComponent(nameDeletedTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(deleteBTN)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        ColourBGPNL.add(deletePNL);
        deletePNL.setBounds(22, 344, 269, 197);

        staffScheduleLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        staffScheduleLBL.setText("Staff Schedule");
        ColourBGPNL.add(staffScheduleLBL);
        staffScheduleLBL.setBounds(22, 594, 101, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsemester2/54088672-healthy-food-background-studio-photo-of-different-fruits-and-vegetables-on-white-wooden-table-high-r.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        ColourBGPNL.add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 1000);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColourBGPNL, javax.swing.GroupLayout.DEFAULT_SIZE, 1197, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ColourBGPNL, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
    // TODO add your handling code here:
    String searchName;
    boolean search = false;
    
    if (list.isEmpty()){
        txtOutput.setText("The staff list is empty."); //display when list is empty
    }
    
    else{
    try{
    searchName = searchNameTF.getText(); //prompt user to enter staff name they want to search
            if (searchName.equals("")){
                throw new Exception("This cannot be empty. You must specify name!");
            }
            for(int i = 0; i < list.size(); i++){
            if (searchName.equalsIgnoreCase(list.get(i).staff.getName())){ //compare searchName with name in the data stored in the array
            search = true;
            header = String.format("%-40s%-14s%-20s%-20s%-20s%-20s%-20s%-20s%-20s%-20s\n","NAME","STAFF ID","DUTY","MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY");
            txtOutput.setText(header);    
            txtOutput.append(list.get(i).displaySchedule()); //display staff's data that has been searched  
            }
    }
            if (search == false){
              txtOutput.setText("Staff name is not found!"); //display when there are no name stored in the array that matching with the search name
            }  
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
            }
    } 
    
    }//GEN-LAST:event_searchBTNActionPerformed

    private void searchNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNameTFActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        String nameDeleted;
        boolean delete = false;
        
        if (list.isEmpty()){
            txtOutput.setText("The staff list is empty."); //display when list is empty
        }
        
        else{
        try{
        //prompt user to enter staff name that they want to delete
        nameDeleted = nameDeletedTF.getText();
        if (nameDeleted.equals("")){
                throw new Exception("This cannot be empty. You must specify name!");
            }
        for (int i = 0; i < list.size(); i++){
            if (nameDeleted.equalsIgnoreCase(list.get(i).staff.getName())){ //compare whether the search name entered to delete is match with the name stored in array
                list.remove(i);
                delete = true;
                String s = "The name and all the data has been deleted successfully.";
                JOptionPane.showMessageDialog(null,s);
                writeData();
            }
        }
        if (delete == false){
                txtOutput.setText("Staff name is not found!"); //display when the name searched to be deleted didn't exist
        } 
        }catch (Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
        }
    }
        
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        
        if (list.isEmpty()){
            txtOutput.setText("The staff list is empty."); //display when list is empty
        }
        
        else{
        header = String.format("%-40s%-14s%-20s%-20s%-20s%-20s%-20s%-20s%-20s%-20s\n","NAME","STAFF ID","DUTY","MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY");
        txtOutput.setText(header);    
        for(int i = 0; i < list.size(); i++)
        {   
            txtOutput.append(list.get(i).displaySchedule()); //print all the staff name and their schedule that stored in the array
        } //end for loop
        }   
    }//GEN-LAST:event_displayBTNActionPerformed

    private void OKbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbtnActionPerformed
        // TODO add your handling code here:
        try{
        //prompt user to enter how many numbers of morning staff, middle staff and evening staff.
        morningStaff = Integer.parseInt(morningStaffTF.getText());
        middleStaff = Integer.parseInt(middleStaffTF.getText());
        eveningStaff = Integer.parseInt(eveningStaffTF.getText());
        if (morningStaff < 0 || middleStaff < 0 || eveningStaff < 0){  
                 throw new Exception("Invalid Input! number of morning/evening/middle staff should greater than 0. Cannot use NEGATIVE number.");
        }
        txtOutput.setText("Attention!! Please make sure there are " +morningStaff+ " staff for every morning shift, \n"+middleStaff+ " staff for middle shift and "+eveningStaff+ " staff for evening shift.");
        writeData();
        
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);       
        }
        
    }//GEN-LAST:event_OKbtnActionPerformed

    private void resetShiftBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetShiftBTNActionPerformed
        // TODO add your handling code here:
        morningStaffTF.setText("");
        middleStaffTF.setText("");
        eveningStaffTF.setText("");
    }//GEN-LAST:event_resetShiftBTNActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        // TODO add your handling code here:
        String updateName;
        boolean edit = false;
        
        try{
        if (list.isEmpty()){
            txtOutput.setText("The staff list is empty."); //display when list is empty
        }

        else{
            //prompt user to enter staff name that they want to edit
            updateName = editedNameTF.getText();
            if (updateName.equals("")){
                throw new Exception("This cannot be empty. You must specify name!");
            }
            for (int i = 0; i < list.size(); i++){
                if (updateName.equalsIgnoreCase(list.get(i).staff.getName())){
                    try{
                    //Enter new name, staff id, duty and shift for Monday till Sunday to be edited
                    String nameUpdated = staffNameTF.getText();
                    list.get(i).staff.name = nameUpdated;
                    String staffIDUpdated = staffIDTF.getText();
                    list.get(i).staff.staffID = staffIDUpdated;
                    String dutyUpdated = dutyCB.getSelectedItem().toString();
                    list.get(i).staff.duty = dutyUpdated;
                    String shiftday1Updated = shiftMondayTF.getText();
                    list.get(i).shiftday1 = shiftday1Updated;
                    String shiftday2Updated = shiftTuesdayTF.getText();
                    list.get(i).shiftday2 = shiftday2Updated;
                    String shiftday3Updated = shiftWedTF.getText();
                    list.get(i).shiftday3 = shiftday3Updated;
                    String shiftday4Updated = shiftThursdayTF.getText();
                    list.get(i).shiftday4 = shiftday4Updated;
                    String shiftday5Updated = shiftFridayTF.getText();
                    list.get(i).shiftday5 = shiftday5Updated;
                    String shiftday6Updated = shiftSatTF.getText();
                    list.get(i).shiftday6 = shiftday6Updated;
                    String shiftday7Updated = shiftSundayTF.getText();
                    list.get(i).shiftday7 = shiftday7Updated;
                    if (nameUpdated.equals("") || staffIDUpdated.equals("") || dutyUpdated.equals("") || shiftday1Updated.equals("") || shiftday2Updated.equals("") || shiftday3Updated.equals("") || shiftday4Updated.equals("") || shiftday5Updated.equals("") || shiftday6Updated.equals("") || shiftday7Updated.equals("")){
                    throw new Exception("Text field cannot be empty!");
                    }
                    edit = true;
                    header = String.format("%-40s%-14s%-20s%-20s%-20s%-20s%-20s%-20s%-20s%-20s\n","NAME","STAFF ID","DUTY","MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY");
                    txtOutput.setText(header);
                    txtOutput.append(list.get(i).displaySchedule());
                    String s = "The data has been updated successfully.";
                    JOptionPane.showMessageDialog(null,s); 
                    writeData();
                    }catch (Exception e){
                    JOptionPane.showMessageDialog(null,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
                    }
                }
            }
            if (edit == false){
                txtOutput.setText("Staff name is not found!"); //display when the name searched to be edited didn't exist
            }
        }
                    }catch (Exception e){
                    JOptionPane.showMessageDialog(null,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE); 
                    }
    }//GEN-LAST:event_updateBTNActionPerformed

    private void resetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTNActionPerformed
        // TODO add your handling code here:

        //clear text field and text area
        staffNameTF.setText("");
        staffIDTF.setText("");
        shiftMondayTF.setText("");
        shiftTuesdayTF.setText("");
        shiftWedTF.setText("");
        shiftThursdayTF.setText("");
        shiftFridayTF.setText("");
        shiftSatTF.setText("");
        shiftSundayTF.setText("");
        txtOutput.setText("");
        searchNameTF.setText("");
        editedNameTF.setText("");
        nameDeletedTF.setText("");

    }//GEN-LAST:event_resetBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        
        try{
        //prompt user to enter staff details to be added
        name = staffNameTF.getText();
        staffID = staffIDTF.getText();
        duty = dutyCB.getSelectedItem().toString();
        shiftday1 = shiftMondayTF.getText();
        shiftday2 = shiftTuesdayTF.getText();
        shiftday3 = shiftWedTF.getText();
        shiftday4 = shiftThursdayTF.getText();
        shiftday5 = shiftFridayTF.getText();
        shiftday6 = shiftSatTF.getText();
        shiftday7 = shiftSundayTF.getText();
        //create object for Staff class and JobSchedule class
        if (name.equals("") || staffID.equals("") || duty.equals("") || shiftday1.equals("") || shiftday2.equals("") || shiftday3.equals("") || shiftday4.equals("") || shiftday5.equals("") || shiftday6.equals("") || shiftday7.equals("")){
                throw new Exception("Text field cannot be empty!");
            }
        staff = new Staff(name, staffID, duty);
        js = new JobSchedule(staff, shiftday1, shiftday2, shiftday3, shiftday4, shiftday5, shiftday6, shiftday7);
        list.add(js); //assign JobSchedule to arraylist
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        writeData();
    }//GEN-LAST:event_addBTNActionPerformed

    private void dutyCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dutyCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dutyCBActionPerformed
    
    private void loadData(){
        try {
            File file = new File("output.txt"); //create file
            FileReader f = new FileReader(file);
            StringBuffer sb = new StringBuffer();
            while (f.ready()) {
                char c = (char) f.read();
                if (c == '-') {
                  String jobscharray[] = sb.toString().split(",");                       
                  list.add(new JobSchedule(
                                    staff,
                                    jobscharray[1],
                                    jobscharray[2],
                                    jobscharray[3],
                                    jobscharray[4],
                                    jobscharray[5],
                                    jobscharray[5],
                                    jobscharray[6]));
                        
                  sb = new StringBuffer();
                }else{
                  sb.append(c);
               }
            }
            f.close();       
           }catch(IOException e){
              return;
        }  
     }

    private void writeData(){
     StringBuilder sb = new StringBuilder();           
     try  {
         FileWriter f = new FileWriter("output.txt");
         String s = "";   
         for (int i = 0; i < list.size(); i++)
            sb.append(list.get(i).displaySchedule());
            f.write(sb.toString());
            f.close();
        }catch(IOException e){
            return;
        }
        
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobScheduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobScheduleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ColourBGPNL;
    private javax.swing.JButton OKbtn;
    private javax.swing.JPanel ShiftDetailsPNL;
    private javax.swing.JButton addBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JPanel deletePNL;
    private javax.swing.JLabel deletedNameLBL;
    private javax.swing.JLabel detailsShiftLBL;
    private javax.swing.JButton displayBTN;
    private javax.swing.JComboBox dutyCB;
    private javax.swing.JLabel dutyLBL;
    private javax.swing.JLabel editNameLBL;
    private javax.swing.JTextField editedNameTF;
    private javax.swing.JLabel eveningLBL;
    private javax.swing.JLabel eveningStaffLBL;
    private javax.swing.JTextField eveningStaffTF;
    private javax.swing.JLabel eveningTimeLBL;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel fridayLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel middleLBL;
    private javax.swing.JLabel middleStaffLBL;
    private javax.swing.JTextField middleStaffTF;
    private javax.swing.JLabel middleTimeLBL;
    private javax.swing.JLabel mondayLBL;
    private javax.swing.JLabel morningLBL;
    private javax.swing.JLabel morningStaffLBL;
    private javax.swing.JTextField morningStaffTF;
    private javax.swing.JLabel morningTimeLBL;
    private javax.swing.JTextField nameDeletedTF;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JButton resetBTN;
    private javax.swing.JButton resetShiftBTN;
    private javax.swing.JLabel restaurantNameLBL;
    private javax.swing.JLabel saturdayLBL;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel searchNameLBL;
    private javax.swing.JTextField searchNameTF;
    private javax.swing.JPanel searchPNL;
    private javax.swing.JPanel shiftAndTimePNL;
    private javax.swing.JLabel shiftDetailsLBL;
    private javax.swing.JTextField shiftFridayTF;
    private javax.swing.JLabel shiftLBL;
    private javax.swing.JTextField shiftMondayTF;
    private javax.swing.JTextField shiftSatTF;
    private javax.swing.JTextField shiftSundayTF;
    private javax.swing.JTextField shiftThursdayTF;
    private javax.swing.JLabel shiftTimeLBL;
    private javax.swing.JTextField shiftTuesdayTF;
    private javax.swing.JTextField shiftWedTF;
    private javax.swing.JPanel staffDetailsandShiftPNL;
    private javax.swing.JLabel staffIDLBL;
    private javax.swing.JTextField staffIDTF;
    private javax.swing.JTextField staffNameTF;
    private javax.swing.JLabel staffScheduleLBL;
    private javax.swing.JPanel staffSchedulePNL;
    private javax.swing.JLabel sundayLBL;
    private javax.swing.JLabel thursdayLBL;
    private javax.swing.JLabel timeLBL;
    private javax.swing.JLabel tuesdayLBL;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JButton updateBTN;
    private javax.swing.JPanel updatePNL;
    private javax.swing.JLabel wednesdayLBL;
    // End of variables declaration//GEN-END:variables
}
