package assignment3;

public class TestJobSchedule extends javax.swing.JFrame {

    /**
     * Creates new form TestJobSchedule
     */
        JobSchedule[] jobs = new JobSchedule[100]; //create array of object for class Staff
        Staff staff; 
        JobSchedule js;
        //variable declaration
        int morningStaff;
        int middleStaff;
        int eveningStaff;
        String name;
        String staffID;
        String duty;
        String shiftday1;
        String shiftday2;
        String shiftday3;
        String shiftday4;
        String shiftday5;
        String shiftday6;
        String shiftday7;
        //initialize count to 0
        int count = 0;
        
    public TestJobSchedule() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        morningStaffLBL = new javax.swing.JLabel();
        middleStaffLBL = new javax.swing.JLabel();
        eveningStaffLBL = new javax.swing.JLabel();
        morningStaffTF = new javax.swing.JTextField();
        middleStaffTF = new javax.swing.JTextField();
        eveningStaffTF = new javax.swing.JTextField();
        OKbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        displayBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        nameLBL = new javax.swing.JLabel();
        staffIDLBL = new javax.swing.JLabel();
        dutyLBL = new javax.swing.JLabel();
        staffNameTF = new javax.swing.JTextField();
        staffIDTF = new javax.swing.JTextField();
        mondayLBL = new javax.swing.JLabel();
        tuesdayLBL = new javax.swing.JLabel();
        wednesdayLBL = new javax.swing.JLabel();
        thursdayLBL = new javax.swing.JLabel();
        fridayLBL = new javax.swing.JLabel();
        saturdayLBL = new javax.swing.JLabel();
        sundayLBL = new javax.swing.JLabel();
        shiftMondayTF = new javax.swing.JTextField();
        shiftTuesdayTF = new javax.swing.JTextField();
        shiftWedTF = new javax.swing.JTextField();
        shiftThursdayTF = new javax.swing.JTextField();
        shiftFridayTF = new javax.swing.JTextField();
        shiftSatTF = new javax.swing.JTextField();
        shiftSundayTF = new javax.swing.JTextField();
        dutyCB = new javax.swing.JComboBox();
        addBTN = new javax.swing.JButton();
        resetBTN = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        editBTN = new javax.swing.JButton();
        editedNameTF = new javax.swing.JTextField();
        editNameLBL = new javax.swing.JLabel();
        restaurantNameLBL = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        shiftLBL = new javax.swing.JLabel();
        timeLBL = new javax.swing.JLabel();
        morningLBL = new javax.swing.JLabel();
        middleLBL = new javax.swing.JLabel();
        eveningLBL = new javax.swing.JLabel();
        morningTimeLBL = new javax.swing.JLabel();
        middleTimeLBL = new javax.swing.JLabel();
        eveningTimeLBL = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        searchNameTF = new javax.swing.JTextField();
        searchBTN = new javax.swing.JButton();
        searchNameLBL = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        nameDeletedTF = new javax.swing.JTextField();
        deleteBTN = new javax.swing.JButton();
        deletedNameLBL = new javax.swing.JLabel();
        detailsShiftLBL = new javax.swing.JLabel();
        shiftTimeLBL = new javax.swing.JLabel();
        staffScheduleLBL = new javax.swing.JLabel();
        shiftDetailsLBL = new javax.swing.JLabel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                                                                                                     Job Schedule");
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        morningStaffLBL.setText("Morning shift staff :");

        middleStaffLBL.setText("Middle shift staff :");

        eveningStaffLBL.setText("Evening shift staff :");

        OKbtn.setBackground(new java.awt.Color(255, 153, 204));
        OKbtn.setText("OK");
        OKbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(middleStaffTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(middleStaffLBL)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(morningStaffLBL)
                            .addGap(18, 18, 18)
                            .addComponent(morningStaffTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eveningStaffLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eveningStaffTF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OKbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(morningStaffLBL)
                    .addComponent(morningStaffTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleStaffLBL)
                    .addComponent(middleStaffTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eveningStaffTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eveningStaffLBL))
                .addGap(23, 23, 23)
                .addComponent(OKbtn)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOutput.setEditable(false);
        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        displayBTN.setBackground(new java.awt.Color(255, 153, 204));
        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        exitBTN.setBackground(new java.awt.Color(255, 153, 204));
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(displayBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                        .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayBTN)
                    .addComponent(exitBTN))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nameLBL.setText("Name :");

        staffIDLBL.setText("Staff ID :");

        dutyLBL.setText("Duty :");

        mondayLBL.setText("Monday : ");

        tuesdayLBL.setText("Tuesday :");

        wednesdayLBL.setText("Wednesday :");

        thursdayLBL.setText("Thursday :");

        fridayLBL.setText("Friday :");

        saturdayLBL.setText("Saturday :");

        sundayLBL.setText("Sunday :");

        dutyCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kitchen", "Lobby" }));
        dutyCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dutyCBActionPerformed(evt);
            }
        });

        addBTN.setBackground(new java.awt.Color(255, 153, 204));
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        resetBTN.setBackground(new java.awt.Color(255, 153, 204));
        resetBTN.setText("Reset");
        resetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTNActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        editBTN.setBackground(new java.awt.Color(255, 153, 204));
        editBTN.setText("Edit");
        editBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTNActionPerformed(evt);
            }
        });

        editNameLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        editNameLBL.setText("Enter staff name to be edited :");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editNameLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(editedNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(editNameLBL)
                .addGap(18, 18, 18)
                .addComponent(editedNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(editBTN)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saturdayLBL)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wednesdayLBL)
                                    .addComponent(thursdayLBL)
                                    .addComponent(fridayLBL)
                                    .addComponent(sundayLBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(shiftSundayTF, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(shiftFridayTF)
                                    .addComponent(shiftThursdayTF)
                                    .addComponent(shiftSatTF)
                                    .addComponent(shiftWedTF))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mondayLBL)
                                    .addComponent(tuesdayLBL))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(shiftMondayTF, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(shiftTuesdayTF)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dutyLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dutyCB, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(staffIDLBL)
                                    .addComponent(nameLBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(staffNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(staffIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLBL)
                            .addComponent(staffNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staffIDLBL)
                            .addComponent(staffIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dutyLBL)
                            .addComponent(dutyCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mondayLBL)
                            .addComponent(shiftMondayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tuesdayLBL)
                            .addComponent(shiftTuesdayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wednesdayLBL)
                    .addComponent(shiftWedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thursdayLBL)
                    .addComponent(shiftThursdayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shiftFridayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fridayLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saturdayLBL)
                    .addComponent(shiftSatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sundayLBL)
                    .addComponent(shiftSundayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(resetBTN))
                .addContainerGap())
        );

        restaurantNameLBL.setBackground(new java.awt.Color(255, 255, 255));
        restaurantNameLBL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        restaurantNameLBL.setText("CHE SITI WAN KEMBANG RESTAURANT");

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        shiftLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        shiftLBL.setText("Shift");

        timeLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        timeLBL.setText("Time");

        morningLBL.setText("Morning");

        middleLBL.setText("Middle");

        eveningLBL.setText("Evening");

        morningTimeLBL.setText("9AM - 6PM");

        middleTimeLBL.setText("12PM - 8PM");

        eveningTimeLBL.setText("2PM - 11PM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shiftLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(morningLBL)
                    .addComponent(middleLBL)
                    .addComponent(eveningLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(morningTimeLBL)
                        .addComponent(middleTimeLBL)
                        .addComponent(eveningTimeLBL))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(timeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shiftLBL)
                    .addComponent(timeLBL))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(morningLBL)
                    .addComponent(morningTimeLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleLBL)
                    .addComponent(middleTimeLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eveningLBL)
                    .addComponent(eveningTimeLBL))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameTFActionPerformed(evt);
            }
        });

        searchBTN.setBackground(new java.awt.Color(255, 153, 204));
        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        searchNameLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        searchNameLBL.setText("Enter staff name to search :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(searchNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchNameLBL)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchNameLBL)
                .addGap(28, 28, 28)
                .addComponent(searchNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(searchBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        deleteBTN.setBackground(new java.awt.Color(255, 153, 204));
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        deletedNameLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deletedNameLBL.setText("Enter staff name to be deleted :");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deletedNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(nameDeletedTF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletedNameLBL)
                .addGap(28, 28, 28)
                .addComponent(nameDeletedTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(deleteBTN)
                .addGap(52, 52, 52))
        );

        detailsShiftLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        detailsShiftLBL.setText("Staff Details & Shift");

        shiftTimeLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        shiftTimeLBL.setText("Shift & Time");

        staffScheduleLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        staffScheduleLBL.setText("Staff Schedule");

        shiftDetailsLBL.setBackground(new java.awt.Color(255, 255, 255));
        shiftDetailsLBL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        shiftDetailsLBL.setText("Shift Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(restaurantNameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shiftDetailsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(detailsShiftLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(shiftTimeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(170, 170, 170))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(staffScheduleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(restaurantNameLBL)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(staffScheduleLBL)
                        .addGap(4, 4, 4)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(shiftDetailsLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(shiftTimeLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailsShiftLBL)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
    // TODO add your handling code here:
    String searchName;
    boolean search = false;
    
    if (count == 0){
        txtOutput.setText("The staff list is empty."); //display when list is empty
    }
    
    else{
    searchName = searchNameTF.getText(); //prompt user to enter staff name they want to search
     
    for(int i = 0; i < count; i++){
            if (searchName.equalsIgnoreCase(jobs[i].staff.getName())){ //compare searchName with name in the data stored in the array
            search = true;
            txtOutput.setText(jobs[i].displaySchedule()); //display staff's data that has been searched  
            }
    }
            if (search == false){
              txtOutput.setText("Staff name is not found!"); //display when there are no name stored in the array that matching with the search name
            }  
    } 
    
    }//GEN-LAST:event_searchBTNActionPerformed

    private void searchNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNameTFActionPerformed

    private void dutyCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dutyCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dutyCBActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void resetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTNActionPerformed
        // TODO add your handling code here:
        
        //clear text field and text area
        staffNameTF.setText("");
        staffIDTF.setText("");
        shiftMondayTF.setText("");
        shiftTuesdayTF.setText("");
        shiftWedTF.setText("");
        shiftThursdayTF.setText("");
        shiftFridayTF.setText("");
        shiftSatTF.setText("");
        shiftSundayTF.setText("");
        txtOutput.setText("");
        searchNameTF.setText("");
        editedNameTF.setText("");
        nameDeletedTF.setText("");
        
    }//GEN-LAST:event_resetBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        if (count < jobs.length){
            
            //prompt user to enter staff details to be added
            name = staffNameTF.getText();
            staffID = staffIDTF.getText();
            duty = dutyCB.getSelectedItem().toString();
            shiftday1 = shiftMondayTF.getText();
            shiftday2 = shiftTuesdayTF.getText();
            shiftday3 = shiftWedTF.getText();
            shiftday4 = shiftThursdayTF.getText();
            shiftday5 = shiftFridayTF.getText();
            shiftday6 = shiftSatTF.getText();
            shiftday7 = shiftSundayTF.getText();
            staff = new Staff(name, staffID, duty);//create object for class Staff
            js = new JobSchedule(staff, shiftday1, shiftday2, shiftday3, shiftday4, shiftday5, shiftday6, shiftday7);//create object for class JobSchedule
            jobs[count] = js; //assign JobSchedule to array
            count++; //count will increment when user add data
        }
        else{
            txtOutput.setText(""); 
            txtOutput.setText("Error. Sorry, list is FULL!"); //display when list is full
        }
    }//GEN-LAST:event_addBTNActionPerformed

    private void editBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTNActionPerformed
        // TODO add your handling code here:
        String editName;
        boolean edit = false;
        
        if (count == 0){
            txtOutput.setText("The staff list is empty."); //display when list is empty
        }
        
        else{
        //prompt user to enter staff name that they want to edit
        editName = editedNameTF.getText();   
        
        for (int i = 0; i < count; i++){
            if (editName.equalsIgnoreCase(jobs[i].staff.getName())){
                 //Enter new name, staff id, duty and shift for Monday till Sunday to be edited
                String nameEdited = staffNameTF.getText();
                jobs[i].staff.name = nameEdited;
                String staffIDEdited = staffIDTF.getText();
                jobs[i].staff.staffID = staffIDEdited;
                String dutyEdited = dutyCB.getSelectedItem().toString();
                jobs[i].staff.duty = dutyEdited;
                String shiftday1Edited = shiftMondayTF.getText();
                jobs[i].shiftday1 = shiftday1Edited;
                String shiftday2Edited = shiftTuesdayTF.getText() ;
                jobs[i].shiftday2 = shiftday2Edited;        
                String shiftday3Edited = shiftWedTF.getText() ;
                jobs[i].shiftday3 = shiftday3Edited;
                String shiftday4Edited = shiftThursdayTF.getText() ;
                jobs[i].shiftday4 = shiftday4Edited;
                String shiftday5Edited = shiftFridayTF.getText() ;
                jobs[i].shiftday5 = shiftday5Edited;
                String shiftday6Edited = shiftSatTF.getText() ;
                jobs[i].shiftday6 = shiftday6Edited;
                String shiftday7Edited = shiftSundayTF.getText();
                jobs[i].shiftday7 = shiftday7Edited;    
                edit = true;
                txtOutput.setText(jobs[i].displaySchedule() + "\nThe data has been edited successfully."); 
            }
        }
        if (edit == false){
            txtOutput.setText("Staff name is not found!"); //display when the name searched to be edited didn't exist
        }
        }
    }//GEN-LAST:event_editBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        String nameDeleted;
        boolean delete = false;
        
        if (count == 0){
            txtOutput.setText("The staff list is empty."); //display when list is empty
        }
        
        else{
        //prompt user to enter staff name that they want to delete
        nameDeleted = nameDeletedTF.getText();
        for (int i = 0; i < count; i++){
            if (nameDeleted.equalsIgnoreCase(jobs[i].staff.getName())){ //compare whether the search name entered to delete is match with the name stored in array
                
        for (int j = i; j < count-1; j++ )
                jobs[j] = jobs[j+1];
                --count;
                delete = true;
                txtOutput.setText("The name and all the data has been deleted successfully."); 
            }
        }
        if (delete == false)
                txtOutput.setText("Staff name is not found!"); //display when the name searched to be deleted didn't exist
        }   
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        
        if (count == 0){
            txtOutput.setText("The staff list is empty."); //display when list is empty
        }
        
        else{
        for(int i = 0; i < count; i++)
        {   
            txtOutput.append(jobs[i].displaySchedule()); //print all the staff name and their schedule that stored in the array
        } //end for loop
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void OKbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbtnActionPerformed
        // TODO add your handling code here:
        
        //prompt user to enter how many numbers of morning staff, middle staff and evening staff.
        morningStaff = Integer.parseInt(morningStaffTF.getText());
        middleStaff = Integer.parseInt(middleStaffTF.getText());
        eveningStaff = Integer.parseInt(eveningStaffTF.getText());
        
        txtOutput.setText("Attention!! Please make sure there are " +morningStaff+ " staff for every morning shift, \n"+middleStaff+ " staff for middle shift and "+eveningStaff+ " staff for evening shift.");
    }//GEN-LAST:event_OKbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestJobSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestJobSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestJobSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestJobSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestJobSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKbtn;
    private javax.swing.JButton addBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JLabel deletedNameLBL;
    private javax.swing.JLabel detailsShiftLBL;
    private javax.swing.JButton displayBTN;
    private javax.swing.JComboBox dutyCB;
    private javax.swing.JLabel dutyLBL;
    private javax.swing.JButton editBTN;
    private javax.swing.JLabel editNameLBL;
    private javax.swing.JTextField editedNameTF;
    private javax.swing.JLabel eveningLBL;
    private javax.swing.JLabel eveningStaffLBL;
    private javax.swing.JTextField eveningStaffTF;
    private javax.swing.JLabel eveningTimeLBL;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel fridayLBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel middleLBL;
    private javax.swing.JLabel middleStaffLBL;
    private javax.swing.JTextField middleStaffTF;
    private javax.swing.JLabel middleTimeLBL;
    private javax.swing.JLabel mondayLBL;
    private javax.swing.JLabel morningLBL;
    private javax.swing.JLabel morningStaffLBL;
    private javax.swing.JTextField morningStaffTF;
    private javax.swing.JLabel morningTimeLBL;
    private javax.swing.JTextField nameDeletedTF;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JButton resetBTN;
    private javax.swing.JLabel restaurantNameLBL;
    private javax.swing.JLabel saturdayLBL;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel searchNameLBL;
    private javax.swing.JTextField searchNameTF;
    private javax.swing.JLabel shiftDetailsLBL;
    private javax.swing.JTextField shiftFridayTF;
    private javax.swing.JLabel shiftLBL;
    private javax.swing.JTextField shiftMondayTF;
    private javax.swing.JTextField shiftSatTF;
    private javax.swing.JTextField shiftSundayTF;
    private javax.swing.JTextField shiftThursdayTF;
    private javax.swing.JLabel shiftTimeLBL;
    private javax.swing.JTextField shiftTuesdayTF;
    private javax.swing.JTextField shiftWedTF;
    private javax.swing.JLabel staffIDLBL;
    private javax.swing.JTextField staffIDTF;
    private javax.swing.JTextField staffNameTF;
    private javax.swing.JLabel staffScheduleLBL;
    private javax.swing.JLabel sundayLBL;
    private javax.swing.JLabel thursdayLBL;
    private javax.swing.JLabel timeLBL;
    private javax.swing.JLabel tuesdayLBL;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JLabel wednesdayLBL;
    // End of variables declaration//GEN-END:variables
}
