/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectdatastructure;


/**
 *
 * @author User-PC
 */
public class LibraryManagementSystemGUI extends javax.swing.JFrame {

    /**
     * Creates new form LibraryManagementSystemGUI
     */
    LibraryList list = new LibraryList();
    Student std;
    Book book;
    String name, id, bookTitleb1, borrowDateb1, returnDateb1, bookTitleb2, borrowDateb2, returnDateb2, bookTitleb3, borrowDateb3, returnDateb3;
    
    public LibraryManagementSystemGUI() {
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        studentDetailsPNL = new javax.swing.JPanel();
        nameLBL = new javax.swing.JLabel();
        idLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        outputPNL = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTA = new javax.swing.JTextArea();
        displayBTN = new javax.swing.JButton();
        bookPNL = new javax.swing.JPanel();
        bookTitleLBL = new javax.swing.JLabel();
        borrowDateLBL = new javax.swing.JLabel();
        returnDateLBL = new javax.swing.JLabel();
        bookTitleb1TF = new javax.swing.JTextField();
        borrowDateb1TF = new javax.swing.JTextField();
        returnDateb1TF = new javax.swing.JTextField();
        bookTitleb2TF = new javax.swing.JTextField();
        borrowDateb2TF = new javax.swing.JTextField();
        returnDateb2TF = new javax.swing.JTextField();
        bookTitleb3TF = new javax.swing.JTextField();
        borrowDateb3TF = new javax.swing.JTextField();
        returnDateb3TF = new javax.swing.JTextField();
        book1LBL = new javax.swing.JLabel();
        book2LBL = new javax.swing.JLabel();
        book3LBL = new javax.swing.JLabel();
        searchTF = new javax.swing.JPanel();
        nameUpdateLBL = new javax.swing.JLabel();
        nameDeleteLBL = new javax.swing.JLabel();
        searchLBL = new javax.swing.JLabel();
        nameUpdateTF = new javax.swing.JTextField();
        updateBTN = new javax.swing.JButton();
        nameDeleteTF = new javax.swing.JTextField();
        searchBTN = new javax.swing.JButton();
        resetBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        nameSearchTF = new javax.swing.JTextField();
        deleteStudentBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                                                             LIBRARY MANAGEMENT SYSTEM");

        jPanel4.setBackground(new java.awt.Color(255, 153, 255));

        studentDetailsPNL.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsPNL.setBorder(javax.swing.BorderFactory.createTitledBorder("STUDENT DETAILS"));

        nameLBL.setText("Name :");

        idLBL.setText("Student ID :");

        addBTN.setBackground(new java.awt.Color(255, 204, 255));
        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentDetailsPNLLayout = new javax.swing.GroupLayout(studentDetailsPNL);
        studentDetailsPNL.setLayout(studentDetailsPNLLayout);
        studentDetailsPNLLayout.setHorizontalGroup(
            studentDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDetailsPNLLayout.createSequentialGroup()
                .addGroup(studentDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLBL)
                    .addComponent(nameLBL))
                .addGroup(studentDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentDetailsPNLLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentDetailsPNLLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentDetailsPNLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        studentDetailsPNLLayout.setVerticalGroup(
            studentDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDetailsPNLLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(studentDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLBL)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentDetailsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLBL)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBTN)
                .addContainerGap())
        );

        outputPNL.setBackground(new java.awt.Color(255, 255, 255));
        outputPNL.setBorder(javax.swing.BorderFactory.createTitledBorder("OUTPUT"));

        outputTA.setColumns(20);
        outputTA.setRows(5);
        jScrollPane2.setViewportView(outputTA);

        displayBTN.setBackground(new java.awt.Color(255, 204, 255));
        displayBTN.setText("DISPLAY");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout outputPNLLayout = new javax.swing.GroupLayout(outputPNL);
        outputPNL.setLayout(outputPNLLayout);
        outputPNLLayout.setHorizontalGroup(
            outputPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outputPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputPNLLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(displayBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        outputPNLLayout.setVerticalGroup(
            outputPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(displayBTN))
        );

        bookPNL.setBackground(new java.awt.Color(255, 255, 255));
        bookPNL.setBorder(javax.swing.BorderFactory.createTitledBorder("BOOK"));

        bookTitleLBL.setText("Book Title");

        borrowDateLBL.setText("Borrow Date ");

        returnDateLBL.setText("Return Date ");

        book1LBL.setText("Book 1:");

        book2LBL.setText("Book 2:");

        book3LBL.setText("Book 3:");

        javax.swing.GroupLayout bookPNLLayout = new javax.swing.GroupLayout(bookPNL);
        bookPNL.setLayout(bookPNLLayout);
        bookPNLLayout.setHorizontalGroup(
            bookPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPNLLayout.createSequentialGroup()
                .addGroup(bookPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bookTitleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(bookPNLLayout.createSequentialGroup()
                        .addGroup(bookPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(book1LBL)
                            .addGroup(bookPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(book2LBL, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(book3LBL)))
                        .addGap(18, 18, 18)
                        .addGroup(bookPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookTitleb3TF, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(bookTitleb2TF)
                            .addComponent(bookTitleb1TF))
                        .addGap(18, 18, 18)))
                .addGroup(bookPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(borrowDateb1TF)
                    .addComponent(borrowDateLBL)
                    .addComponent(borrowDateb2TF)
                    .addComponent(borrowDateb3TF, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(bookPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(returnDateLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateb1TF)
                    .addComponent(returnDateb2TF)
                    .addComponent(returnDateb3TF, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        bookPNLLayout.setVerticalGroup(
            bookPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPNLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bookPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookTitleLBL)
                    .addComponent(borrowDateLBL)
                    .addComponent(returnDateLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookTitleb1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowDateb1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateb1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book1LBL))
                .addGap(18, 18, 18)
                .addGroup(bookPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookTitleb2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowDateb2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateb2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book2LBL))
                .addGap(18, 18, 18)
                .addGroup(bookPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookTitleb3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowDateb3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateb3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book3LBL))
                .addGap(37, 37, 37))
        );

        searchTF.setBackground(new java.awt.Color(255, 255, 255));
        searchTF.setBorder(javax.swing.BorderFactory.createTitledBorder("OPTION"));

        nameUpdateLBL.setText("Search name to update their book title:");

        nameDeleteLBL.setText("Search name to delete their book title:");

        searchLBL.setText("Search to see student details and  their list of book :");

        nameUpdateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameUpdateTFActionPerformed(evt);
            }
        });

        updateBTN.setBackground(new java.awt.Color(255, 204, 255));
        updateBTN.setText("UPDATE");

        nameDeleteTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameDeleteTFActionPerformed(evt);
            }
        });

        searchBTN.setBackground(new java.awt.Color(255, 204, 255));
        searchBTN.setText("SEARCH");

        resetBTN.setBackground(new java.awt.Color(255, 204, 255));
        resetBTN.setText("RESET");
        resetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTNActionPerformed(evt);
            }
        });

        exitBTN.setBackground(new java.awt.Color(255, 204, 255));
        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        nameSearchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchTFActionPerformed(evt);
            }
        });

        deleteStudentBTN.setBackground(new java.awt.Color(255, 204, 255));
        deleteStudentBTN.setText("DELETE");

        javax.swing.GroupLayout searchTFLayout = new javax.swing.GroupLayout(searchTF);
        searchTF.setLayout(searchTFLayout);
        searchTFLayout.setHorizontalGroup(
            searchTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTFLayout.createSequentialGroup()
                .addGroup(searchTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchTFLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resetBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchTFLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(searchTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameUpdateLBL)
                            .addComponent(nameDeleteLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(deleteStudentBTN)
                                .addGroup(searchTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nameSearchTF, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(nameDeleteTF, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(updateBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nameUpdateTF, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchTFLayout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addComponent(searchLBL)
                .addGap(175, 175, 175))
        );
        searchTFLayout.setVerticalGroup(
            searchTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameUpdateLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameUpdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateBTN)
                .addGap(5, 5, 5)
                .addComponent(nameDeleteLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameDeleteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(deleteStudentBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchLBL)
                .addGap(1, 1, 1)
                .addComponent(nameSearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchTFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBTN)
                    .addComponent(exitBTN))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel1.setText("SULTAN BADLI SHAH LIBRARY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(studentDetailsPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bookPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(studentDetailsPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bookPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(searchTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(outputPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
    System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void resetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTNActionPerformed
        // TODO add your handling code here:
    nameTF.setText("");
    idTF.setText("");
    bookTitleb1TF.setText("");
    borrowDateb1TF.setText("");
    returnDateb1TF.setText("");
    bookTitleb2TF.setText("");
    borrowDateb2TF.setText("");
    returnDateb2TF.setText("");
    bookTitleb3TF.setText("");
    borrowDateb3TF.setText("");
    returnDateb3TF.setText("");
    nameUpdateTF.setText("");
    nameDeleteTF.setText("");
    nameSearchTF.setText("");
    outputTA.setText("");
    
    }//GEN-LAST:event_resetBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
    String outFinal;
    outFinal = list.displayData();
    outputTA.append(outFinal);
    
    }//GEN-LAST:event_displayBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
      name = nameTF.getText();
      id = idTF.getText();
      bookTitleb1 = bookTitleb1TF.getText();
      borrowDateb1 = borrowDateb1TF.getText();
      returnDateb1 = returnDateb1TF.getText();
      bookTitleb2 = bookTitleb2TF.getText();
      borrowDateb2 = borrowDateb2TF.getText();
      returnDateb2 = returnDateb2TF.getText();
      bookTitleb3 = bookTitleb3TF.getText();
      borrowDateb3 = borrowDateb3TF.getText();
      returnDateb3 = returnDateb3TF.getText();
      
      std = new Student(name, id);
      book = new Book(std, bookTitleb1, borrowDateb1, returnDateb1, bookTitleb2, borrowDateb2, returnDateb2, bookTitleb3, borrowDateb3, returnDateb3);
      
      list.addFirst(std, book);
    }//GEN-LAST:event_addBTNActionPerformed

    private void nameUpdateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameUpdateTFActionPerformed
        // TODO add your handling code here:
    String nameUpdate = nameUpdateTF.getText();
    
    list.updateByName(nameUpdate);
    }//GEN-LAST:event_nameUpdateTFActionPerformed

    private void nameDeleteTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameDeleteTFActionPerformed
        // TODO add your handling code here:
    String nameDelete = nameDeleteTF.getText();
    
    list.deleteByName(nameDelete);
    }//GEN-LAST:event_nameDeleteTFActionPerformed

    private void nameSearchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSearchTFActionPerformed
        // TODO add your handling code here:
    String nameSearch = nameSearchTF.getText();
     
    list.searchByName(nameSearch);
    }//GEN-LAST:event_nameSearchTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryManagementSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryManagementSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryManagementSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryManagementSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryManagementSystemGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel book1LBL;
    private javax.swing.JLabel book2LBL;
    private javax.swing.JLabel book3LBL;
    private javax.swing.JPanel bookPNL;
    private javax.swing.JLabel bookTitleLBL;
    private javax.swing.JTextField bookTitleb1TF;
    private javax.swing.JTextField bookTitleb2TF;
    private javax.swing.JTextField bookTitleb3TF;
    private javax.swing.JLabel borrowDateLBL;
    private javax.swing.JTextField borrowDateb1TF;
    private javax.swing.JTextField borrowDateb2TF;
    private javax.swing.JTextField borrowDateb3TF;
    private javax.swing.JButton deleteStudentBTN;
    private javax.swing.JButton displayBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel idLBL;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameDeleteLBL;
    private javax.swing.JTextField nameDeleteTF;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameSearchTF;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel nameUpdateLBL;
    private javax.swing.JTextField nameUpdateTF;
    private javax.swing.JPanel outputPNL;
    private javax.swing.JTextArea outputTA;
    private javax.swing.JButton resetBTN;
    private javax.swing.JLabel returnDateLBL;
    private javax.swing.JTextField returnDateb1TF;
    private javax.swing.JTextField returnDateb2TF;
    private javax.swing.JTextField returnDateb3TF;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel searchLBL;
    private javax.swing.JPanel searchTF;
    private javax.swing.JPanel studentDetailsPNL;
    private javax.swing.JButton updateBTN;
    // End of variables declaration//GEN-END:variables
}
