package project_STIA2024;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class BillingSystemTest extends javax.swing.JFrame {

    String billDate, accountNo, invoiceNo, userName, userAddress, meterNo, userInputSearch;
    double overdueAmt, oldMeter, newMeter, totalUsage, totalCharge, totalBill;
    int index, indexArray;

    // arraylist for add data
    ArrayList<BillingSystem> dataBill = new ArrayList<BillingSystem>();
    
    // loadFileToArray()
    ArrayList<BillingSystem> billArrayList = new ArrayList<BillingSystem>();
    

    /**
     * Creates new form BillingSystemTest
     */
    public BillingSystemTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        addDataPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextBillDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextAccNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextInvoiceNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextUserName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextUserAddress = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jTextOverdueAmt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextMeterNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextOldMeter = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextNewMeter = new javax.swing.JTextField();
        submitAddBtn = new javax.swing.JButton();
        resetAddBtn = new javax.swing.JButton();
        editDataPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextSearchEdit = new javax.swing.JTextField();
        searchEditBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextEditBillDate = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextEditAccNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextEditInvoiceNo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextEditUserName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextEditUserAddress = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jTextEditOverdueAmt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextEditMeterNo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextEditOldMeter = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextEditNewMeter = new javax.swing.JTextField();
        editDataBtn = new javax.swing.JButton();
        deleteDataPanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextSearchDelete = new javax.swing.JTextField();
        searchDeleteBtn = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextDeleteBillDate = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextDeleteAccNo = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextDeleteInvoiceNo = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextDeleteUserName = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextDeleteUserAddress = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jTextDeleteOverdueAmt = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextDeleteMeterNo = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextDeleteOldMeter = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextDeleteNewMeter = new javax.swing.JTextField();
        deleteDataBtn = new javax.swing.JButton();
        displayDataPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchDataPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextSearchData = new javax.swing.JTextField();
        searchDataPanelBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        addPanelBtn = new javax.swing.JButton();
        searchPanelBtn = new javax.swing.JButton();
        displayPanelBtn = new javax.swing.JButton();
        editPanelBtn = new javax.swing.JButton();
        deletePanelBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billing Electricity System");
        setBackground(new java.awt.Color(153, 204, 255));

        contentPane.setBackground(new java.awt.Color(153, 204, 255));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.setLayout(new java.awt.CardLayout());

        addDataPanel.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Add Data Form");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Tarikh Bil:  (DD/MM/YYYY)");

        jTextBillDate.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("No Akaun:");

        jTextAccNo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("No Invois Cukai:");

        jTextInvoiceNo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Nama Pengguna:");

        jTextUserName.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Alamat Pengguna:");

        jTextUserAddress.setColumns(20);
        jTextUserAddress.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextUserAddress.setRows(5);
        jScrollPane1.setViewportView(jTextUserAddress);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Tunggakan:");

        jTextOverdueAmt.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setText("No Meter: ");

        jTextMeterNo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("Bacaan Meter Dahulu:");

        jTextOldMeter.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setText("Bacaan Meter Sekarang:");

        jTextNewMeter.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        submitAddBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        submitAddBtn.setText("Submit");
        submitAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAddBtnActionPerformed(evt);
            }
        });

        resetAddBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        resetAddBtn.setText("Reset");
        resetAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetAddBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDataPanelLayout = new javax.swing.GroupLayout(addDataPanel);
        addDataPanel.setLayout(addDataPanelLayout);
        addDataPanelLayout.setHorizontalGroup(
            addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDataPanelLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDataPanelLayout.createSequentialGroup()
                        .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(59, 59, 59)
                        .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextBillDate)
                            .addComponent(jTextAccNo)
                            .addComponent(jTextInvoiceNo)
                            .addComponent(jTextUserName)
                            .addComponent(jTextOverdueAmt)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextMeterNo)
                            .addComponent(jTextOldMeter)
                            .addComponent(jTextNewMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(280, 280, 280))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDataPanelLayout.createSequentialGroup()
                        .addComponent(resetAddBtn)
                        .addGap(18, 18, 18)
                        .addComponent(submitAddBtn)
                        .addGap(143, 143, 143))))
        );
        addDataPanelLayout.setVerticalGroup(
            addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextBillDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextOverdueAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextMeterNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextOldMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextNewMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(addDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetAddBtn)
                    .addComponent(submitAddBtn))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jLayeredPane1.add(addDataPanel, "card2");

        editDataPanel.setBackground(new java.awt.Color(255, 255, 153));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel15.setText("Edit Data Form");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel16.setText("Enter \"No Akaun\" to search the related data");

        jTextSearchEdit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        searchEditBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        searchEditBtn.setText("Search");
        searchEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEditBtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel17.setText("Tarikh Bil:  (DD/MM/YYYY)");

        jTextEditBillDate.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel18.setText("No Akaun:");

        jTextEditAccNo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel19.setText("No Invois Cukai:");

        jTextEditInvoiceNo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel20.setText("Nama Pengguna:");

        jTextEditUserName.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel21.setText("Alamat Pengguna:");

        jTextEditUserAddress.setColumns(20);
        jTextEditUserAddress.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextEditUserAddress.setRows(5);
        jScrollPane4.setViewportView(jTextEditUserAddress);

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel22.setText("Tunggakan:");

        jTextEditOverdueAmt.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel23.setText("No Meter: ");

        jTextEditMeterNo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel24.setText("Bacaan Meter Dahulu:");

        jTextEditOldMeter.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel25.setText("Bacaan Meter Sekarang:");

        jTextEditNewMeter.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        editDataBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        editDataBtn.setText("Edit");
        editDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDataBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editDataPanelLayout = new javax.swing.GroupLayout(editDataPanel);
        editDataPanel.setLayout(editDataPanelLayout);
        editDataPanelLayout.setHorizontalGroup(
            editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDataPanelLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(294, 294, 294))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDataPanelLayout.createSequentialGroup()
                        .addComponent(jTextSearchEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDataPanelLayout.createSequentialGroup()
                        .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editDataBtn)
                            .addComponent(searchEditBtn))
                        .addGap(292, 292, 292))))
            .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editDataPanelLayout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25))
                    .addGap(59, 59, 59)
                    .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextEditBillDate)
                        .addComponent(jTextEditAccNo)
                        .addComponent(jTextEditInvoiceNo)
                        .addComponent(jTextEditUserName)
                        .addComponent(jTextEditOverdueAmt)
                        .addComponent(jScrollPane4)
                        .addComponent(jTextEditMeterNo)
                        .addComponent(jTextEditOldMeter)
                        .addComponent(jTextEditNewMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(103, Short.MAX_VALUE)))
        );
        editDataPanelLayout.setVerticalGroup(
            editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDataPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextSearchEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchEditBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                .addComponent(editDataBtn)
                .addGap(85, 85, 85))
            .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editDataPanelLayout.createSequentialGroup()
                    .addGap(171, 171, 171)
                    .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jTextEditBillDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jTextEditAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jTextEditInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jTextEditUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jTextEditOverdueAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jTextEditMeterNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(jTextEditOldMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(editDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(jTextEditNewMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(172, Short.MAX_VALUE)))
        );

        jLayeredPane1.add(editDataPanel, "card2");

        deleteDataPanel.setBackground(new java.awt.Color(255, 255, 153));

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel26.setText("Delete Data Form");

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel27.setText("Enter \"No Akaun\" to search the related data");

        jTextSearchDelete.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        searchDeleteBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        searchDeleteBtn.setText("Search");
        searchDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDeleteBtnActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel28.setText("Tarikh Bil:  (DD/MM/YYYY)");

        jTextDeleteBillDate.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel29.setText("No Akaun:");

        jTextDeleteAccNo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel30.setText("No Invois Cukai:");

        jTextDeleteInvoiceNo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel31.setText("Nama Pengguna:");

        jTextDeleteUserName.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel32.setText("Alamat Pengguna:");

        jTextDeleteUserAddress.setColumns(20);
        jTextDeleteUserAddress.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextDeleteUserAddress.setRows(5);
        jScrollPane5.setViewportView(jTextDeleteUserAddress);

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel33.setText("Tunggakan:");

        jTextDeleteOverdueAmt.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel34.setText("No Meter: ");

        jTextDeleteMeterNo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel35.setText("Bacaan Meter Dahulu:");

        jTextDeleteOldMeter.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel36.setText("Bacaan Meter Sekarang:");

        jTextDeleteNewMeter.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        deleteDataBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        deleteDataBtn.setText("Delete");
        deleteDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDataBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteDataPanelLayout = new javax.swing.GroupLayout(deleteDataPanel);
        deleteDataPanel.setLayout(deleteDataPanelLayout);
        deleteDataPanelLayout.setHorizontalGroup(
            deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteDataPanelLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(294, 294, 294))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteDataPanelLayout.createSequentialGroup()
                        .addComponent(jTextSearchDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteDataPanelLayout.createSequentialGroup()
                        .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteDataBtn)
                            .addComponent(searchDeleteBtn))
                        .addGap(292, 292, 292))))
            .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deleteDataPanelLayout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28)
                        .addComponent(jLabel29)
                        .addComponent(jLabel30)
                        .addComponent(jLabel31)
                        .addComponent(jLabel32)
                        .addComponent(jLabel33)
                        .addComponent(jLabel34)
                        .addComponent(jLabel35)
                        .addComponent(jLabel36))
                    .addGap(59, 59, 59)
                    .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextDeleteBillDate)
                        .addComponent(jTextDeleteAccNo)
                        .addComponent(jTextDeleteInvoiceNo)
                        .addComponent(jTextDeleteUserName)
                        .addComponent(jTextDeleteOverdueAmt)
                        .addComponent(jScrollPane5)
                        .addComponent(jTextDeleteMeterNo)
                        .addComponent(jTextDeleteOldMeter)
                        .addComponent(jTextDeleteNewMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(103, Short.MAX_VALUE)))
        );
        deleteDataPanelLayout.setVerticalGroup(
            deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteDataPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextSearchDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchDeleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                .addComponent(deleteDataBtn)
                .addGap(85, 85, 85))
            .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deleteDataPanelLayout.createSequentialGroup()
                    .addGap(171, 171, 171)
                    .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jTextDeleteBillDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(jTextDeleteAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(jTextDeleteInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(jTextDeleteUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel32)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(jTextDeleteOverdueAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(jTextDeleteMeterNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(jTextDeleteOldMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(deleteDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(jTextDeleteNewMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(146, Short.MAX_VALUE)))
        );

        jLayeredPane1.add(deleteDataPanel, "card2");

        displayDataPanel.setBackground(new java.awt.Color(255, 255, 153));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setText("Display All Data");

        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout displayDataPanelLayout = new javax.swing.GroupLayout(displayDataPanel);
        displayDataPanel.setLayout(displayDataPanelLayout);
        displayDataPanelLayout.setHorizontalGroup(
            displayDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayDataPanelLayout.createSequentialGroup()
                .addGroup(displayDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayDataPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(displayDataPanelLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel11)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        displayDataPanelLayout.setVerticalGroup(
            displayDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLayeredPane1.add(displayDataPanel, "card2");

        searchDataPanel.setBackground(new java.awt.Color(255, 255, 153));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel13.setText("Search Data Form");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel14.setText("Enter \"No Akaun\" to search.");

        searchDataPanelBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        searchDataPanelBtn.setText("Search");
        searchDataPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDataPanelBtnActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarikh Bil", "No Akaun", "No Invois Cukai", "Nama Pengguna", "Alamat Pengguna", "Tunggakan", "No Meter", "Bacaan Meter Dahulu", "Bacaan Meter Sekarang", "Jumlah Unit Kegunaan", "Caj Semasa", "Jumlah Bayaran Bil"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout searchDataPanelLayout = new javax.swing.GroupLayout(searchDataPanel);
        searchDataPanel.setLayout(searchDataPanelLayout);
        searchDataPanelLayout.setHorizontalGroup(
            searchDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchDataPanelLayout.createSequentialGroup()
                .addGroup(searchDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextSearchData, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(searchDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchDataPanelLayout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(jLabel13))
                            .addGroup(searchDataPanelLayout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jLabel14))))
                    .addGroup(searchDataPanelLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(searchDataPanelBtn))
                    .addGroup(searchDataPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        searchDataPanelLayout.setVerticalGroup(
            searchDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchDataPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextSearchData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchDataPanelBtn)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLayeredPane1.add(searchDataPanel, "card2");

        addPanelBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        addPanelBtn.setText("Add");
        addPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPanelBtnActionPerformed(evt);
            }
        });

        searchPanelBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        searchPanelBtn.setText("Search");
        searchPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPanelBtnActionPerformed(evt);
            }
        });

        displayPanelBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        displayPanelBtn.setText("Display");
        displayPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPanelBtnActionPerformed(evt);
            }
        });

        editPanelBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        editPanelBtn.setText("Edit");
        editPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPanelBtnActionPerformed(evt);
            }
        });

        deletePanelBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        deletePanelBtn.setText("Delete");
        deletePanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePanelBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel12.setText("BILLING ELECTRICITY SYSTEM");

        exitBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGap(76, 247, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(addPanelBtn)
                .addGap(18, 18, 18)
                .addComponent(editPanelBtn)
                .addGap(24, 24, 24)
                .addComponent(deletePanelBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayPanelBtn)
                .addGap(18, 18, 18)
                .addComponent(searchPanelBtn)
                .addGap(18, 18, 18)
                .addComponent(exitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPanelBtn)
                    .addComponent(displayPanelBtn)
                    .addComponent(editPanelBtn)
                    .addComponent(deletePanelBtn)
                    .addComponent(searchPanelBtn)
                    .addComponent(exitBtn))
                .addGap(34, 34, 34)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // PANELS
    private void addPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPanelBtnActionPerformed
        switchPanels(addDataPanel);
        resetField();
    }//GEN-LAST:event_addPanelBtnActionPerformed

    private void searchPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPanelBtnActionPerformed
        switchPanels(searchDataPanel);
    }//GEN-LAST:event_searchPanelBtnActionPerformed

    private void displayPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPanelBtnActionPerformed
        switchPanels(displayDataPanel);
        jTextSearchData.setText("");
        clearDataTable();
        loadFileToTable();
    }//GEN-LAST:event_displayPanelBtnActionPerformed

    private void editPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPanelBtnActionPerformed
        switchPanels(editDataPanel);
        jTextSearchEdit.setText("");
        jTextEditBillDate.setText("");
        jTextEditAccNo.setText("");
        jTextEditInvoiceNo.setText("");
        jTextEditUserName.setText("");
        jTextEditUserAddress.setText("");
        jTextEditOverdueAmt.setText("");
        jTextEditMeterNo.setText("");
        jTextEditOldMeter.setText("");
        jTextEditNewMeter.setText("");
    }//GEN-LAST:event_editPanelBtnActionPerformed

    private void deletePanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePanelBtnActionPerformed
        switchPanels(deleteDataPanel);
        jTextSearchDelete.setText("");
        jTextDeleteBillDate.setText("");
        jTextDeleteAccNo.setText("");
        jTextDeleteInvoiceNo.setText("");
        jTextDeleteUserName.setText("");
        jTextDeleteUserAddress.setText("");
        jTextDeleteOverdueAmt.setText("");
        jTextDeleteMeterNo.setText("");
        jTextDeleteOldMeter.setText("");
        jTextDeleteNewMeter.setText("");
    }//GEN-LAST:event_deletePanelBtnActionPerformed

    // ADD PANEL - button action
    private void submitAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAddBtnActionPerformed
        // empty input from user
        if (jTextBillDate.getText().isEmpty() || jTextAccNo.getText().isEmpty() || jTextInvoiceNo.getText().isEmpty()
                || jTextUserName.getText().isEmpty() || jTextUserAddress.getText().isEmpty() || jTextOverdueAmt.getText().isEmpty()
                || jTextMeterNo.getText().isEmpty() || jTextOldMeter.getText().isEmpty() || jTextNewMeter.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please key in all the data required.",
                        "Data Error!", JOptionPane.ERROR_MESSAGE);
        } 
        else {
            try {
                billDate = jTextBillDate.getText();
                accountNo = jTextAccNo.getText();
                invoiceNo = jTextInvoiceNo.getText();
                userName = jTextUserName.getText();
                userAddress = jTextUserAddress.getText();
                overdueAmt = Double.parseDouble(jTextOverdueAmt.getText());
                meterNo = jTextMeterNo.getText();
                oldMeter = Double.parseDouble(jTextOldMeter.getText());
                newMeter = Double.parseDouble(jTextNewMeter.getText());

                BillingSystem bs = new BillingSystem(overdueAmt, oldMeter, newMeter);
                totalUsage = bs.calculateTotalUsage();
                totalCharge = bs.calculateTotalCharge();
                totalBill = bs.calculateTotalBill();

                // add data into arraylist
                BillingSystem newBill = new BillingSystem(billDate, accountNo, invoiceNo, userName, userAddress, overdueAmt, meterNo,
                        oldMeter, newMeter, totalUsage, totalCharge, totalBill);
                dataBill.add(newBill);

                if (dataBill.contains(newBill)) {
                    // if the data is in the arraylist then add the data to the text.file
                    writeFile("userInputData.txt");
                    int input = JOptionPane.showConfirmDialog(null,
                           "Data Successfully Added", "Success", JOptionPane.DEFAULT_OPTION);
                    // 0=ok
                    if (input == 0) {
                        resetField();
                    } else {
                        JOptionPane.showConfirmDialog(null, "Process Failed", "Fail", JOptionPane.ERROR_MESSAGE);
                    }
                }

                } catch (NumberFormatException numberFormatException) {
                    JOptionPane.showMessageDialog(null, "Please key in all the data required.",
                        "Data Error!", JOptionPane.ERROR_MESSAGE);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "System Error");
                }
            }
    }//GEN-LAST:event_submitAddBtnActionPerformed

    private void resetAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetAddBtnActionPerformed
        resetField();
    }//GEN-LAST:event_resetAddBtnActionPerformed

    // SEARCH PANEL - button action
    private void searchDataPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDataPanelBtnActionPerformed
        try {
            String searchData = jTextSearchData.getText();
            binarySearch(searchData, "search");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "System Error");
        }
    }//GEN-LAST:event_searchDataPanelBtnActionPerformed
    
    // EDIT PANEL - button action
    private void searchEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEditBtnActionPerformed
        try {
            String editData = jTextSearchEdit.getText();
            binarySearch(editData, "edit");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "System Error");
        }
    }//GEN-LAST:event_searchEditBtnActionPerformed

    private void editDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDataBtnActionPerformed
        String editTerm = jTextSearchEdit.getText();
        
        String updatebillDate = jTextEditBillDate.getText();
        String updateaccountNo =jTextEditAccNo.getText();
        String updateinvoiceNo = jTextEditInvoiceNo.getText();
        String updateuserName = jTextEditUserName.getText();
        String updateuserAddress = jTextEditUserAddress.getText();
        double updateoverdueAmt = Double.parseDouble(jTextEditOverdueAmt.getText());
        String updatemeterNo = jTextEditMeterNo.getText();
        double updateoldMeter = Double.parseDouble(jTextEditOldMeter.getText());
        double updatenewMeter = Double.parseDouble(jTextEditNewMeter.getText());

        BillingSystem bs = new BillingSystem(updateoverdueAmt, updateoldMeter, updatenewMeter);
        totalUsage = bs.calculateTotalUsage();
        totalCharge = bs.calculateTotalCharge();
        totalBill = bs.calculateTotalBill();

        String tempFile = "tempt.txt";
        String filePath = "userInputData.txt";
            
        File oldFile = new File (filePath);
        File newFile = new File (tempFile);
            
        try {
            FileWriter fw = new FileWriter(tempFile, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
                 
            FileReader fr = new FileReader(filePath);
            BufferedReader br = new BufferedReader(fr);
                 
            String currentLine;
            String data[];
                
            while ((currentLine = br.readLine()) != null) {
            data = currentLine.split(" # ");
            if ((data[1].equals(editTerm))) {
                pw.println(String.format("%s", updatebillDate) + " # " + String.format("%s", updateaccountNo) + " # " + String.format("%s", updateinvoiceNo) + " # "
                            + String.format("%s", updateuserName) + " # " + String.format("%s", updateuserAddress) + " # " + String.format("%.2f",  updateoverdueAmt) + " # "
                            + String.format("%s", updatemeterNo) + " # " + String.format("%.0f", updateoldMeter) + " # " + String.format("%.0f", updatenewMeter) + " # " 
                            + String.format("%.0f", totalUsage)  + " # " + String.format("%.2f", totalCharge) + " # " + String.format("%.2f",  totalBill )); 
                }
                
                else {
                    pw.println(currentLine);
                }
            }   
            
            pw.flush();
            pw.close();
            fr.close();
            br.close();
            bw.close();
            fw.close();
            
            oldFile.delete();
            newFile.renameTo(oldFile);
            
            int input = JOptionPane.showConfirmDialog(null,
                        "Data successfully edited", "Success", JOptionPane.DEFAULT_OPTION);
                // 0=ok
                if (input == 0) {
                    jTextSearchEdit.setText("");
                    jTextEditBillDate.setText("");
                    jTextEditAccNo.setText("");
                    jTextEditInvoiceNo.setText("");
                    jTextEditUserName.setText("");
                    jTextEditUserAddress.setText("");
                    jTextEditOverdueAmt.setText("");
                    jTextEditMeterNo.setText("");
                    jTextEditOldMeter.setText("");
                    jTextEditNewMeter.setText("");
                } else {
                    JOptionPane.showConfirmDialog(null, "Process Failed", "Fail", JOptionPane.ERROR_MESSAGE);
                }  
            }
            catch (IOException e) {
            JOptionPane.showConfirmDialog(null, "Operation Fail", "Fail", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editDataBtnActionPerformed

    // DELETE PANEL - button action
    private void searchDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDeleteBtnActionPerformed
        try {
            String deleteData = jTextSearchDelete.getText();
            binarySearch(deleteData, "delete");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "System Error");
        }
    }//GEN-LAST:event_searchDeleteBtnActionPerformed

    private void deleteDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDataBtnActionPerformed
        String removeTerm = jTextSearchDelete.getText();

        String filePath = "userInputData.txt";
        String tempFile = "temp.txt";
        File oldFile = new File ( filePath );
        File newFile = new File ( tempFile );
        String currentLine;
        String data[];

        try {
            FileWriter fw = new FileWriter ( tempFile , true );
            BufferedWriter bw = new BufferedWriter ( fw );
            PrintWriter pw = new PrintWriter ( bw );

            FileReader fr = new FileReader ( filePath );
            BufferedReader br = new BufferedReader ( fr );

            while (( currentLine = br.readLine ( ) ) != null) {
                data = currentLine.split ( " # " );
                if ( !( data[1].equalsIgnoreCase ( removeTerm ) ) ) {
                    pw.println ( currentLine );
                }
            }
            pw.flush ( );
            pw.close ( );
            fr.close ( );
            br.close ( );
            bw.close ( );
            fw.close ( );

            oldFile.delete ( );
            newFile.renameTo ( oldFile );
            int input = JOptionPane.showConfirmDialog(null,
                        "Data successfully deleted", "Success", JOptionPane.DEFAULT_OPTION);
                // 0=ok
                if (input == 0) {
                    jTextSearchDelete.setText("");
                    jTextDeleteBillDate.setText("");
                    jTextDeleteAccNo.setText("");
                    jTextDeleteInvoiceNo.setText("");
                    jTextDeleteUserName.setText("");
                    jTextDeleteUserAddress.setText("");
                    jTextDeleteOverdueAmt.setText("");
                    jTextDeleteMeterNo.setText("");
                    jTextDeleteOldMeter.setText("");
                    jTextDeleteNewMeter.setText("");

                } else {
                    JOptionPane.showConfirmDialog(null, "Process Failed", "Fail", JOptionPane.ERROR_MESSAGE);
                }  
            
            } catch ( IOException e ) {
            JOptionPane.showMessageDialog ( null , "File not found" , "Error" , JOptionPane.ERROR_MESSAGE );
            }
    }//GEN-LAST:event_deleteDataBtnActionPerformed

    // EXIT FROM SYSTEM
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    // METHOD
    // switching between panels
    public void switchPanels(JPanel panel) {
        jLayeredPane1.removeAll();
        jLayeredPane1.add(panel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }

    // ADD PANEL
    // add data to txt file
    private void writeFile(String fileName) throws IOException {
        BufferedWriter bw = new BufferedWriter(new FileWriter(fileName, true));
        bw.write(String.format("%s", billDate) + " # " + String.format("%s", accountNo) + " # " + String.format("%s", invoiceNo) + " # "
                + String.format("%s", userName) + " # " + String.format("%s", userAddress) + " # " + String.format("%.2f", overdueAmt) + " # "
                + String.format("%s", meterNo) + " # " + String.format("%.0f", oldMeter) + " # " + String.format("%.0f", newMeter) + " # "
                + String.format("%.0f", totalUsage) + " # " + String.format("%.2f", totalCharge) + " # " + String.format("%.2f", totalBill));
        bw.flush();
        bw.newLine();
        bw.close();

        sortTextFile();
    }

    // reset text field to blanks
    private void resetField() {
        jTextBillDate.setText("");
        jTextAccNo.setText("");
        jTextInvoiceNo.setText("");
        jTextUserName.setText("");
        jTextUserAddress.setText("");
        jTextOverdueAmt.setText("");
        jTextMeterNo.setText("");
        jTextOldMeter.setText("");
        jTextNewMeter.setText("");
    }
    
    // DISPLAY PANEL
    // clear data in table rows
    private void clearDataTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
        model2.setRowCount(0);
    }
    
    // sort data from userInputData.txt and rewrite in ASCENDING on userOutputData.txt
    private void sortTextFile() throws FileNotFoundException, IOException {
        BufferedReader reader = new BufferedReader(new FileReader("userInputData.txt"));

        ArrayList<BillingSystem> billRecords = new ArrayList<BillingSystem>();

        String currentLine = reader.readLine();

        while (currentLine != null) {
            String[] billDetail = currentLine.split(" # ");

            billDate = billDetail[0];
            accountNo = billDetail[1];
            invoiceNo = billDetail[2];
            userName = billDetail[3];
            userAddress = billDetail[4];
            overdueAmt = Double.valueOf(billDetail[5]);
            meterNo = billDetail[6];
            oldMeter = Double.valueOf(billDetail[7]);
            newMeter = Double.valueOf(billDetail[8]);
            totalUsage = Double.valueOf(billDetail[9]);
            totalCharge = Double.valueOf(billDetail[10]);
            totalBill = Double.valueOf(billDetail[11]);

            billRecords.add(new BillingSystem(billDate, accountNo, invoiceNo, userName, userAddress, overdueAmt, meterNo, oldMeter, newMeter, totalUsage, totalCharge, totalBill));

            currentLine = reader.readLine();
        }

        Collections.sort(billRecords, new AccNoCompare());

        BufferedWriter writer = new BufferedWriter(new FileWriter("userOutputData.txt"));

        for (BillingSystem bill : billRecords) {
            writer.write(bill.billDate + " , " + bill.accountNo + " , " + bill.invoiceNo + " , " + bill.userName + " , " + bill.userAddress + " , " + bill.overdueAmt
                    + " , " + bill.meterNo + " , " + bill.oldMeter + " , " + bill.newMeter + " , " + bill.totalUsage + " , " + bill.totalCharge + " , " + bill.totalBill);
            writer.newLine();
        }

        reader.close();
        writer.close();
    }
    
    // load data from userOutputData.txt into jTable
    private void loadFileToTable() {
        jTable1.clearSelection();
        try {
            sortTextFile();
            BufferedReader br = new BufferedReader(new FileReader("userOutputData.txt"));
            String[] columnsName = {"Tarikh Bil", "No Akaun", "No Invois Cukai", "Nama Pengguna", "Alamat Pengguna",
                "Tunggakan", "No Meter", "Bacaan Meter Dahulu", "Bacaan Meter Sekarang", "Jumlah Unit Kegunaan",
                "Caj Semasa", "Jumlah Bayaran Bil"};
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setColumnIdentifiers(columnsName);

            Object[] tableLines = br.lines().toArray();
            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(" , ");
                model.addRow(dataRow);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BillingSystemTest.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BillingSystemTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // SEARCH PANEL
    // load data from userOutputData.txt to billArrayList
    private void loadFileToArray() throws FileNotFoundException, IOException{
        // load data into arraylist
        BufferedReader reader = new BufferedReader(new FileReader("userOutputData.txt"));

        String currentLine = reader.readLine();

        while (currentLine != null) {
            String[] billDetail = currentLine.split(" , ");

            billDate = billDetail[0];
            accountNo = billDetail[1];
            invoiceNo = billDetail[2];
            userName = billDetail[3];
            userAddress = billDetail[4];
            overdueAmt = Double.valueOf(billDetail[5]);
            meterNo = billDetail[6];
            oldMeter = Double.valueOf(billDetail[7]);
            newMeter = Double.valueOf(billDetail[8]);
            totalUsage = Double.valueOf(billDetail[9]);
            totalCharge = Double.valueOf(billDetail[10]);
            totalBill = Double.valueOf(billDetail[11]);

            billArrayList.add(new BillingSystem(billDate, accountNo, invoiceNo, userName, userAddress, overdueAmt, meterNo, oldMeter, newMeter, totalUsage, totalCharge, totalBill));

            currentLine = reader.readLine();
        }
        reader.close();
    }
    
    // perform binary search
    private void binarySearch(String input, String process) throws IOException{
        loadFileToArray();
        String action = process;
        
        if (billArrayList.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty List");
        } else {
            try {
                index = Collections.binarySearch(billArrayList,
                        new BillingSystem(null, input, null, null, null, 0, null, 0, 0, 0, 0, 0), new AccNoCompare());
                if (action.equals("search")){
                    loadArrayToTable(index);
                }
                else if (action.equals("edit") || action.equals("delete")){
                    loadArrayToTextfield(index, action);
                }
                
            } catch (ArrayIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(null, "Data Not Found");
                if (action.equals("edit")){
                    jTextSearchEdit.setText("");
                    jTextEditBillDate.setText("");
                    jTextEditAccNo.setText("");
                    jTextEditInvoiceNo.setText("");
                    jTextEditUserName.setText("");
                    jTextEditUserAddress.setText("");
                    jTextEditOverdueAmt.setText("");
                    jTextEditMeterNo.setText("");
                    jTextEditOldMeter.setText("");
                    jTextEditNewMeter.setText("");
                }
            }
        }
        jTextSearchData.setText("");
    }
    
    // load data from billArrayList into jTable
    private void loadArrayToTable(int indexArray) throws IOException{
        clearDataTable();
        int i = indexArray;
        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
        Object rowData[] = new Object [12];
        rowData[0] = billArrayList.get(i).billDate;
        rowData[1] = billArrayList.get(i).accountNo;
        rowData[2] = billArrayList.get(i).invoiceNo;
        rowData[3] = billArrayList.get(i).userName;
        rowData[4] = billArrayList.get(i).userAddress;
        rowData[5] = billArrayList.get(i).overdueAmt;
        rowData[6] = billArrayList.get(i).meterNo;
        rowData[7] = billArrayList.get(i).oldMeter;
        rowData[8] = billArrayList.get(i).newMeter;
        rowData[9] = billArrayList.get(i).totalUsage;
        rowData[10] = billArrayList.get(i).totalCharge;
        rowData[11] = billArrayList.get(i).totalBill;
        model2.addRow(rowData);
    }
    
    // EDIT PANEL & DELETE PANEL
    // load data from billArrayList to respective text field based on type of action
    private void loadArrayToTextfield (int indexArray, String process){
        String action = process;
        int i = indexArray;
        
        if (action.equals("edit")) {
            jTextEditBillDate.setText(billArrayList.get(i).billDate);
            jTextEditAccNo.setText(billArrayList.get(i).accountNo);
            jTextEditInvoiceNo.setText(billArrayList.get(i).invoiceNo);
            jTextEditUserName.setText(billArrayList.get(i).userName);
            jTextEditUserAddress.setText(billArrayList.get(i).userAddress);
            jTextEditOverdueAmt.setText(String.valueOf(billArrayList.get(i).overdueAmt));
            jTextEditMeterNo.setText(billArrayList.get(i).meterNo);
            jTextEditOldMeter.setText(String.valueOf(billArrayList.get(i).oldMeter));
            jTextEditNewMeter.setText(String.valueOf(billArrayList.get(i).newMeter));
        }
        else if (action.equals("delete")){
            jTextDeleteBillDate.setText(billArrayList.get(i).billDate);
            jTextDeleteAccNo.setText(billArrayList.get(i).accountNo);
            jTextDeleteInvoiceNo.setText(billArrayList.get(i).invoiceNo);
            jTextDeleteUserName.setText(billArrayList.get(i).userName);
            jTextDeleteUserAddress.setText(billArrayList.get(i).userAddress);
            jTextDeleteOverdueAmt.setText(String.valueOf(billArrayList.get(i).overdueAmt));
            jTextDeleteMeterNo.setText(billArrayList.get(i).meterNo);
            jTextDeleteOldMeter.setText(String.valueOf(billArrayList.get(i).oldMeter));
            jTextDeleteNewMeter.setText(String.valueOf(billArrayList.get(i).newMeter));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingSystemTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingSystemTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingSystemTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingSystemTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingSystemTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addDataPanel;
    private javax.swing.JButton addPanelBtn;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton deleteDataBtn;
    private javax.swing.JPanel deleteDataPanel;
    private javax.swing.JButton deletePanelBtn;
    private javax.swing.JPanel displayDataPanel;
    private javax.swing.JButton displayPanelBtn;
    private javax.swing.JButton editDataBtn;
    private javax.swing.JPanel editDataPanel;
    private javax.swing.JButton editPanelBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextAccNo;
    private javax.swing.JTextField jTextBillDate;
    private javax.swing.JTextField jTextDeleteAccNo;
    private javax.swing.JTextField jTextDeleteBillDate;
    private javax.swing.JTextField jTextDeleteInvoiceNo;
    private javax.swing.JTextField jTextDeleteMeterNo;
    private javax.swing.JTextField jTextDeleteNewMeter;
    private javax.swing.JTextField jTextDeleteOldMeter;
    private javax.swing.JTextField jTextDeleteOverdueAmt;
    private javax.swing.JTextArea jTextDeleteUserAddress;
    private javax.swing.JTextField jTextDeleteUserName;
    private javax.swing.JTextField jTextEditAccNo;
    private javax.swing.JTextField jTextEditBillDate;
    private javax.swing.JTextField jTextEditInvoiceNo;
    private javax.swing.JTextField jTextEditMeterNo;
    private javax.swing.JTextField jTextEditNewMeter;
    private javax.swing.JTextField jTextEditOldMeter;
    private javax.swing.JTextField jTextEditOverdueAmt;
    private javax.swing.JTextArea jTextEditUserAddress;
    private javax.swing.JTextField jTextEditUserName;
    private javax.swing.JTextField jTextInvoiceNo;
    private javax.swing.JTextField jTextMeterNo;
    private javax.swing.JTextField jTextNewMeter;
    private javax.swing.JTextField jTextOldMeter;
    private javax.swing.JTextField jTextOverdueAmt;
    private javax.swing.JTextField jTextSearchData;
    private javax.swing.JTextField jTextSearchDelete;
    private javax.swing.JTextField jTextSearchEdit;
    private javax.swing.JTextArea jTextUserAddress;
    private javax.swing.JTextField jTextUserName;
    private javax.swing.JButton resetAddBtn;
    private javax.swing.JPanel searchDataPanel;
    private javax.swing.JButton searchDataPanelBtn;
    private javax.swing.JButton searchDeleteBtn;
    private javax.swing.JButton searchEditBtn;
    private javax.swing.JButton searchPanelBtn;
    private javax.swing.JButton submitAddBtn;
    // End of variables declaration//GEN-END:variables
}